name: 'Custom AWS Login'
description: 'A custom GitHub Action to perform AWS login.'

inputs:
  dev_account:
    description: 'AWS account ID for the login'
  stg_account:
    description: 'AWS account ID for the login'
  prod_account:
    description: 'AWS account ID for the login'
  dev_role_secret:
    description: 'AWS IAM Role secret for the login'
  stg_role_secret:
    description: 'AWS IAM Role secret for the login'
  prod_role_secret:
    description: 'AWS IAM Role secret for the login'

outputs:
  tfvars:
    description: 'TF var name for the target environment (exported from the action)'
    value: ${{ steps.aws_env.outputs.tfvars }}
  artifact_bucket:
    description: 'Artifact bucket name for the target environment (exported from the action)'
    value: ${{ steps.aws_env.outputs.artifact_bucket }}

runs:
  using: "composite"
  steps:
    - name: Define the name of the variables to be retrieved based on the target environment
      id: aws_env
      shell: bash
      run: |
        # Choose the correct account and role inputs based on ENV_NAME
        case "${ENV_NAME,,}" in
          dev)
            ACCOUNT="${{ inputs.dev_account }}"
            ROLE_SECRET="${{ inputs.dev_role_secret }}"
            ;;
          stg)
            ACCOUNT="${{ inputs.stg_account }}"
            ROLE_SECRET="${{ inputs.stg_role_secret }}"
            ;;
          prod)
            ACCOUNT="${{ inputs.prod_account }}"
            ROLE_SECRET="${{ inputs.prod_role_secret }}"
            ;;
          *)
            echo "Unknown ENV_NAME '${ENV_NAME}', defaulting to 'dev'"
            ACCOUNT="${{ inputs.dev_account }}"
            ROLE_SECRET="${{ inputs.dev_role_secret }}"
            ;;
        esac
        echo "tfvars=${ENV_NAME^^}_TF_VARS" | tee -a $GITHUB_OUTPUT
        echo "artifact_bucket=${ENV_NAME^^}_ARTIFACT_BUCKET" | tee -a $GITHUB_OUTPUT
        ROLE_PREFIX="gha-role-for-$(echo "${REPO_NAME}" | cut -c1-26)-${ENV_NAME}-GHARole"
        echo "arn=arn:aws:iam::${ACCOUNT}:role/${ROLE_PREFIX}-${ROLE_SECRET}" | tee -a $GITHUB_OUTPUT

    - name: AWS CLI Login
      uses: aws-actions/configure-aws-credentials@d4695650384537945e0b565ee73a714d361bcb04  # v5.5.1
      with:
        role-to-assume: ${{ steps.aws_env.outputs.arn }}
        aws-region: ${{ env.AWS_REGION }}
        role-duration-seconds: '3600'
